name: "guy-build-info"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JFROG_CLI_BUILD_PROJECT: ${{ secrets.JFROG_CLI_BUILD_PROJECT }}
      JFROG_CLI_EXTRACTORS_REMOTE: ${{ secrets.JFROG_CLI_EXTRACTORS_REMOTE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JF_ENV_1 }}
          JFROG_CLI_BUILD_PROJECT: ${{ secrets.JFROG_CLI_BUILD_PROJECT }}
      - name: Setup gradle
        run: |
          jf gradlec
      - name: Test
        run: |
          jf gradle clean test
      - name: Build
        run: |
          jf gradle clean build -x test
      - name: Publish
        run: |
          jf rt u build/libs/spring-petclinic-2.6.0-plain.jar guy-gradle-virtual
      - name: Run JFrog CLI
        run: |
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
